### ISSUE TITLE
Feature: playing multiple sounds at once

### ISSUE THREAD

**Issue by richard-kramer** [dominikks/discord-soundboard-bot#6]
While using the board, we often encountered sounds being accidentally overwriten by other users. Maybe it's possible to allow any sound to be played without aborting the previous one?

**Comment by dominikks** [comment]
This should be a straightforward thing to implement and seems sensible to me. 

IIRC there was no "Stop"-button in earlier versions of the soundboard, so overwriting a sound with a new one was the only way to stop it. This was crucial for stopping some of the minute-long sounds we had...

**Comment by dominikks** [comment]
Implement in #10.
